version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: nestjs-db
    restart: always
    environment:
      POSTGRES_USER: maja
      POSTGRES_PASSWORD: mojprvilinux
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'